### ISSUE TITLE
Suggestion : TTLCache pour Vélodi

### ISSUE THREAD

**Issue by AntoineAugusti** [filau/python_divia_api#1]
Salut !

Merci pour ce package ! Je souhaite récupérer les données de disponibilités pour toutes les stations en une fois.

Le code actuel n'est pas optimisé pour ce cas d'usage car une requête HTTP est effectuée pour chaque `station.check()`

https://github.com/filau/python_divia_api/blob/4ffc462c5154218325034100949c87fee2f75bcc/divia_api/velodi.py#L46-L53

L'appel à `update_source` n'est nécessaire que si les données sont expirées, la page sur le site de Divia semblant avoir elle aussi une forme de cache.

Voici le monkey patch que j'ai fait localement en utilisant un [TTLCache de cachedtools](https://cachetools.readthedocs.io/en/stable/#cachetools.TTLCache) si jamais tu es intéressé.

Récupérer les données de toutes les stations dans une boucle ne fait plus qu'une seule requête HTTP.

```py
import divia_api
from divia_api import DiviaAPI
from divia_api.velodi import update_source as update_source
from cachetools import cached, TTLCache

import math


@cached(cache=TTLCache(ttl=30, maxsize=math.inf))
def cached_update_source():
    return update_source()


divia_api.velodi.update_source = cached_update_source


velodi_api = DiviaAPI().velodi
for station in velodi_api.stations:
    availability = station.check()
    print(station.code, station.friendly_name, availability.bikes, availability.docks)

```

**Comment by filau** [comment]
Je vous remercie pour cette suggestion. 
Le module pourrait effectivement être bien mieux optimisé pour cet usage. 
Jʼimplémenterai une solution à ce problème dans la prochaine version du module.

**Comment by filau** [comment]
Bonsoir,  

Afin de ne pas devoir effectuer une nouvelle requête à chaque fois, de nouvelles fonctions ont été ajoutées dans [la version 2.1](https://github.com/filau/python_divia_api/releases/tag/2.1) (commit 20c7fa5).

Vous pouvez donc, en théorie, utiliser ce code dans votre cas :
```python
import divia_api
from divia_api import DiviaAPI

import math


velodi_api = DiviaAPI().velodi
velodi_api.check_multiple_stations(velodi_api.stations)  # Vous obtenez alors une liste d’objets « FreeVelodi » que vous pouvez traiter comme d’habitude.
```

Je documenterai publiquement ces fonctions dans les prochains jours dans le [README](https://github.com/filau/python_divia_api/blob/main/README.md).  

N’hésitez pas à rouvrir le ticket si la solution proposée ne correspond pas bien à votre suggestion&nbsp;!
